// ITEMS DATABASE - DRAINED TABLET ULTIMATE v7.0.0
// Copyright 2026 Casey Steward (CooseTheGeek). All Rights Reserved.
// Complete item list for Rust Console Edition – all 553+ items accessible by owners.

class ItemsDatabase {
    constructor() {
        this.items = this.loadAllItems();
    }

    loadAllItems() {
        return [
            // ===== AMMO =====
            { shortname: 'ammo.shotgun', name: '12 Gauge Buckshot', category: 'Ammo', stack: 64, blueprint: true },
            { shortname: 'ammo.shotgun.fire', name: '12 Gauge Incendiary Shell', category: 'Ammo', stack: 64, blueprint: true },
            { shortname: 'ammo.shotgun.slug', name: '12 Gauge Slug', category: 'Ammo', stack: 64, blueprint: true },
            { shortname: 'ammo.grenadelauncher.he', name: '40mm HE Grenade', category: 'Ammo', stack: 6, blueprint: true },
            { shortname: 'ammo.grenadelauncher.buckshot', name: '40mm Shotgun Round', category: 'Ammo', stack: 6, blueprint: true },
            { shortname: 'ammo.grenadelauncher.smoke', name: '40mm Smoke Grenade', category: 'Ammo', stack: 6, blueprint: true },
            { shortname: 'ammo.rifle', name: '5.56 Rifle Ammo', category: 'Ammo', stack: 128, blueprint: true },
            { shortname: 'arrow.bone', name: 'Bone Arrow', category: 'Ammo', stack: 64, blueprint: true },
            { shortname: 'ammo.rifle.explosive', name: 'Explosive 5.56 Rifle Ammo', category: 'Ammo', stack: 64, blueprint: true },
            { shortname: 'arrow.fire', name: 'Fire Arrow', category: 'Ammo', stack: 64, blueprint: true },
            { shortname: 'ammo.handmade.shell', name: 'Handmade Shell', category: 'Ammo', stack: 64, blueprint: true },
            { shortname: 'arrow.hv', name: 'High Velocity Arrow', category: 'Ammo', stack: 64, blueprint: true },
            { shortname: 'ammo.rocket.hv', name: 'High Velocity Rocket', category: 'Ammo', stack: 3, blueprint: true },
            { shortname: 'ammo.rocket.seeker', name: 'Homing Missile', category: 'Ammo', stack: 1, blueprint: false },
            { shortname: 'ammo.rifle.hv', name: 'HV 5.56 Rifle Ammo', category: 'Ammo', stack: 128, blueprint: true },
            { shortname: 'ammo.pistol.hv', name: 'HV Pistol Ammo', category: 'Ammo', stack: 128, blueprint: true },
            { shortname: 'ammo.rifle.incendiary', name: 'Incendiary 5.56 Rifle Ammo', category: 'Ammo', stack: 64, blueprint: true },
            { shortname: 'ammo.pistol.fire', name: 'Incendiary Pistol Bullet', category: 'Ammo', stack: 64, blueprint: true },
            { shortname: 'ammo.rocket.fire', name: 'Incendiary Rocket', category: 'Ammo', stack: 3, blueprint: true },
            { shortname: 'ammo.rocket.mlrs', name: 'MLRS Rocket', category: 'Ammo', stack: 1, blueprint: false },
            { shortname: 'ammo.nailgun.nails', name: 'Nailgun Nails', category: 'Ammo', stack: 128, blueprint: true },
            { shortname: 'ammo.pistol', name: 'Pistol Bullet', category: 'Ammo', stack: 128, blueprint: true },
            { shortname: 'ammo.rocket.basic', name: 'Rocket', category: 'Ammo', stack: 3, blueprint: true },
            { shortname: 'ammo.rocket.sam', name: 'SAM Ammo', category: 'Ammo', stack: 1, blueprint: false },
            { shortname: 'submarine.torpedo.straight', name: 'Torpedo', category: 'Ammo', stack: 1, blueprint: false },
            { shortname: 'arrow.wooden', name: 'Wooden Arrow', category: 'Ammo', stack: 64, blueprint: true },

            // ===== WEAPONS & ATTACHMENTS =====
            { shortname: 'weapon.mod.small.scope', name: '4x Zoom Scope', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'weapon.mod.burstmodule', name: 'Burst Module', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'weapon.mod.extendedmags', name: 'Extended Magazine', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'weapon.mod.holosight', name: 'Holosight', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'weapon.mod.muzzleboost', name: 'Muzzle Boost', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'weapon.mod.muzzlebrake', name: 'Muzzle Brake', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'weapon.mod.simplesight', name: 'Simple Handmade Sight', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'weapon.mod.silencer', name: 'Silencer', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'weapon.mod.flashlight', name: 'Weapon Flashlight', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'weapon.mod.lasersight', name: 'Weapon Lasersight', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'rifle.ak', name: 'Assault Rifle', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'grenade.beancan', name: 'Beancan Grenade', category: 'Weapons', stack: 3, blueprint: true },
            { shortname: 'blunderbuss', name: 'Blunderbuss', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'rifle.bolt', name: 'Bolt Action Rifle', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'bone.club', name: 'Bone Club', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'knife.bone', name: 'Bone Knife', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'knife.combat', name: 'Combat Knife', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'bow.compound', name: 'Compound Bow', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'crossbow', name: 'Crossbow', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'smg.2', name: 'Custom SMG', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'shotgun.double', name: 'Double Barrel Shotgun', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'pistol.eoka', name: 'Eoka Pistol', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'grenade.f1', name: 'F1 Grenade', category: 'Weapons', stack: 3, blueprint: true },
            { shortname: 'flamethrower', name: 'Flame Thrower', category: 'Weapons', stack: 1, blueprint: false },
            { shortname: 'grenade.flashbang', name: 'Flashbang', category: 'Weapons', stack: 3, blueprint: true },
            { shortname: 't1_smg', name: 'Handmade SMG', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'revolver.hc', name: 'High Caliber Revolver', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'hmlmg', name: 'HMLMG', category: 'Weapons', stack: 1, blueprint: false },
            { shortname: 'homingmissile.launcher', name: 'Homing Missile Launcher', category: 'Weapons', stack: 1, blueprint: false },
            { shortname: 'bow.hunting', name: 'Hunting Bow', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'rifle.l96', name: 'L96 Rifle', category: 'Weapons', stack: 1, blueprint: false },
            { shortname: 'longsword', name: 'Longsword', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'rifle.lr300', name: 'LR-300 Assault Rifle', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'lmg.m249', name: 'M249', category: 'Weapons', stack: 1, blueprint: false },
            { shortname: 'rifle.m39', name: 'M39 Rifle', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'shotgun.m4', name: 'M4 Shotgun', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'pistol.m92', name: 'M92 Pistol', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'mace', name: 'Mace', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'machete', name: 'Machete', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'military flamethrower', name: 'Military Flamethrower', category: 'Weapons', stack: 1, blueprint: false },
            { shortname: 'minigun', name: 'Minigun', category: 'Weapons', stack: 1, blueprint: false },
            { shortname: 'grenade.molotov', name: 'Molotov Cocktail', category: 'Weapons', stack: 3, blueprint: true },
            { shortname: 'smg.mp5', name: 'MP5A4', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'multiplegrenadelauncher', name: 'Multiple Grenade Launcher', category: 'Weapons', stack: 1, blueprint: false },
            { shortname: 'pistol.nailgun', name: 'Nailgun', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'paddle', name: 'Paddle', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'pistol.prototype17', name: 'Prototype 17', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'shotgun.pump', name: 'Pump Shotgun', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'pistol.python', name: 'Python Revolver', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'pistol.revolver', name: 'Revolver', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'rocket.launcher', name: 'Rocket Launcher', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'salvaged.cleaver', name: 'Salvaged Cleaver', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'salvaged.sword', name: 'Salvaged Sword', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'pistol.semiauto', name: 'Semi-Automatic Pistol', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'rifle.semiauto', name: 'Semi-Automatic Rifle', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'knife.skinning', name: 'Skinning Knife', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'rifle.sks', name: 'SKS', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'shotgun.spas12', name: 'Spas-12 Shotgun', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'speargun', name: 'Speargun', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'spear.stone', name: 'Stone Spear', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'smg.thompson', name: 'Thompson', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'shotgun.waterpipe', name: 'Waterpipe Shotgun', category: 'Weapons', stack: 1, blueprint: true },
            { shortname: 'spear.wooden', name: 'Wooden Spear', category: 'Weapons', stack: 1, blueprint: true },

            // ===== CONSTRUCTION =====
            { shortname: 'door.hinged.toptier', name: 'Armored Door', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'door.double.hinged.toptier', name: 'Armored Double Door', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'barricade.woodwire', name: 'Barbed Wooden Barricade', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'building.planner', name: 'Building Plan', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'wall.frame.fence', name: 'Chainlink Fence', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'wall.frame.fence.gate', name: 'Chainlink Fence Gate', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'lock.code', name: 'Code Lock', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'barricade.concrete', name: 'Concrete Barricade', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'floor.grill', name: 'Floor Grill', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'floor.triangle.grill', name: 'Floor Triangle Grill', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'wall.frame.garagedoor', name: 'Garage Door', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'gates.external.high.stone', name: 'High External Stone Gate', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'gates.external.high.wood', name: 'High External Wooden Gate', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'wall.external.high.stone', name: 'High External Stone Wall', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'wall.external.high', name: 'High External Wooden Wall', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'lock.key', name: 'Key Lock', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'floor.ladder.hatch', name: 'Ladder Hatch', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'water.catcher.large', name: 'Large Water Catcher', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'barricade.metal', name: 'Metal Barricade', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'shutter.metal.embrasure.a', name: 'Metal Horizontal Embrasure', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'wall.frame.shopfront.metal', name: 'Metal Shop Front', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'shutter.metal.embrasure.b', name: 'Metal Vertical Embrasure', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'wall.window.bars.metal', name: 'Metal Window Bars', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'wall.frame.netting', name: 'Netting', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'wall.frame.cell.gate', name: 'Prison Cell Gate', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'wall.frame.cell', name: 'Prison Cell Wall', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'wall.window.bars.toptier', name: 'Reinforced Glass Window', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'barricade.sandbags', name: 'Sandbag Barricade', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'door.hinged.metal', name: 'Sheet Metal Door', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'door.double.hinged.metal', name: 'Sheet Metal Double Door', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'wall.frame.shopfront', name: 'Shop Front', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'water.catcher.small', name: 'Small Water Catcher', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'barricade.stone', name: 'Stone Barricade', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'wall.window.glass.reinforced', name: 'Strengthened Glass Window', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'cupboard.tool', name: 'Tool Cupboard', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'floor.triangle.ladder.hatch', name: 'Triangle Ladder Hatch', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'watchtower.wood', name: 'Watch Tower', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'door.double.hinged.wood', name: 'Wood Double Door', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'shutter.wood.a', name: 'Wood Shutters', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'barricade.wood', name: 'Wooden Barricade', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'barricade.wood.cover', name: 'Wooden Barricade Cover', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'door.hinged.wood', name: 'Wooden Door', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'door.double.hinged.bardoors', name: 'Wooden Frontier Bar Doors', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'ladder.wooden.wall', name: 'Wooden Ladder', category: 'Construction', stack: 1, blueprint: true },
            { shortname: 'wall.window.bars.wood', name: 'Wooden Window Bars', category: 'Construction', stack: 1, blueprint: true },
        ];
    }
}            // ===== ITEMS (Deployables, Resources, Attire, Tools, Food, etc.) =====
            
            // Items (continued)
            { shortname: 'bbq', name: 'Barbeque', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'bathtub.planter', name: 'Bath Tub Planter', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'bed', name: 'Bed', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'gunrack.single.1.horizontal', name: 'Bolts Single Item Rack', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'botabag', name: 'Bota Bag', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'campfire', name: 'Camp Fire', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'chair', name: 'Chair', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'dropbox', name: 'Drop Box', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'fishtrophy', name: 'Fish Trophy', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'fridge', name: 'Fridge', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'furnace', name: 'Furnace', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'hitchtroughcombo', name: 'Hitch & Trough', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'storage_barrel_c', name: 'Horizontal Storage Barrel', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'gunrack.horizontal', name: 'Horizontal Weapon Rack', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'gunrack.single.3.horizontal', name: 'Horns Single Item Rack', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'gunrack.single.2.horizontal', name: 'Horseshoe Single Item Rack', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'kayak', name: 'Kayak', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'kits.machine', name: 'Kits Machine', category: 'Items', stack: 1, blueprint: false },
            { shortname: 'lantern', name: 'Lantern', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'furnace.large', name: 'Large Furnace', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'huntingtrophylarge', name: 'Large Hunting Trophy', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'planter.large', name: 'Large Planter Box', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'box.wooden.large', name: 'Large Wood Box', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'locker', name: 'Locker', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'mailbox', name: 'Mail Box', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'minecart.planter', name: 'Minecart Planter', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'mixingtable', name: 'Mixing Table', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'box.repair.bench', name: 'Repair Bench', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'research.table', name: 'Research Table', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'rhib', name: 'RHIB', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'rockingchair', name: 'Rocking Chair', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'rowboat', name: 'Rowboat', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'rug.bear', name: 'Rug Bear Skin', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'rug', name: 'Rug', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'shelves', name: 'Salvaged Shelves', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'skull_fire_pit', name: 'Skull Fire Pit', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'sleepingbag', name: 'Sleeping Bag', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'huntingtrophysmall', name: 'Small Hunting Trophy', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'planter.small', name: 'Small Planter Box', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'small.oil.refinery', name: 'Small Oil Refinery', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'stash.small', name: 'Small Stash', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'fireplace.stone', name: 'Stone Fireplace', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'fishtrap.small', name: 'Survival Fish Trap', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'table', name: 'Table', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'gunrack_tall.horizontal', name: 'Tall Weapon Rack', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'torchholder', name: 'Torch Holder', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'planter.triangle', name: 'Triangle Planter Box', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'tunalight', name: 'Tuna Can Lamp', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'vending.machine', name: 'Vending Machine', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'storage_barrel_b', name: 'Vertical Storage Barrel', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'water.barrel', name: 'Water Barrel', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'water.purifier', name: 'Water Purifier', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'gunrack_stand', name: 'Weapon Rack Stand', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'gunrack_wide.horizontal', name: 'Wide Weapon Rack', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'box.wooden', name: 'Wood Storage Box', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'workbench1', name: 'Workbench Level 1', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'workbench2', name: 'Workbench Level 2', category: 'Items', stack: 1, blueprint: true },
            { shortname: 'workbench3', name: 'Workbench Level 3', category: 'Items', stack: 1, blueprint: true },

            // ===== RESOURCES =====
            { shortname: 'fat.animal', name: 'Animal Fat', category: 'Resources', stack: 1000, blueprint: false },
            { shortname: 'bone.fragments', name: 'Bone Fragments', category: 'Resources', stack: 1000, blueprint: false },
            { shortname: 'cctv.camera', name: 'CCTV Camera', category: 'Resources', stack: 1, blueprint: false },
            { shortname: 'charcoal', name: 'Charcoal', category: 'Resources', stack: 1000, blueprint: false },
            { shortname: 'cloth', name: 'Cloth', category: 'Resources', stack: 1000, blueprint: false },
            { shortname: 'crude.oil', name: 'Crude Oil', category: 'Resources', stack: 100, blueprint: false },
            { shortname: 'diesel_barrel', name: 'Diesel Fuel', category: 'Resources', stack: 1, blueprint: false },
            { shortname: 'can.beans.empty', name: 'Empty Can Of Beans', category: 'Resources', stack: 10, blueprint: false },
            { shortname: 'can.tuna.empty', name: 'Empty Tuna Can', category: 'Resources', stack: 10, blueprint: false },
            { shortname: 'explosives', name: 'Explosives', category: 'Resources', stack: 10, blueprint: true },
            { shortname: 'fertilizer', name: 'Fertilizer', category: 'Resources', stack: 100, blueprint: false },
            { shortname: 'gunpowder', name: 'Gun Powder', category: 'Resources', stack: 1000, blueprint: true },
            { shortname: 'metal.refined', name: 'High Quality Metal', category: 'Resources', stack: 100, blueprint: false },
            { shortname: 'hq.metal.ore', name: 'High Quality Metal Ore', category: 'Resources', stack: 100, blueprint: false },
            { shortname: 'horsedung', name: 'Horse Dung', category: 'Resources', stack: 10, blueprint: false },
            { shortname: 'skull.human', name: 'Human Skull', category: 'Resources', stack: 1, blueprint: false },
            { shortname: 'leather', name: 'Leather', category: 'Resources', stack: 100, blueprint: true },
            { shortname: 'lowgradefuel', name: 'Low Grade Fuel', category: 'Resources', stack: 500, blueprint: true },
            { shortname: 'metal.fragments', name: 'Metal Fragments', category: 'Resources', stack: 1000, blueprint: false },
            { shortname: 'metal.ore', name: 'Metal Ore', category: 'Resources', stack: 1000, blueprint: false },
            { shortname: 'plantfiber', name: 'Plant Fiber', category: 'Resources', stack: 1000, blueprint: false },
            { shortname: 'water.salt', name: 'Salt Water', category: 'Resources', stack: 100, blueprint: false },
            { shortname: 'scrap', name: 'Scrap', category: 'Resources', stack: 1000, blueprint: false },
            { shortname: 'stones', name: 'Stones', category: 'Resources', stack: 1000, blueprint: false },
            { shortname: 'sulfur.ore', name: 'Sulfur Ore', category: 'Resources', stack: 1000, blueprint: false },
            { shortname: 'sulfur', name: 'Sulfur', category: 'Resources', stack: 1000, blueprint: false },
            { shortname: 'targeting.computer', name: 'Targeting Computer', category: 'Resources', stack: 1, blueprint: false },
            { shortname: 'water', name: 'Water', category: 'Resources', stack: 100, blueprint: false },
            { shortname: 'skull.wolf', name: 'Wolf Skull', category: 'Resources', stack: 1, blueprint: false },
            { shortname: 'wood', name: 'Wood', category: 'Resources', stack: 1000, blueprint: false },

            // ===== ATTIRE =====
            { shortname: 'mask.bandana', name: 'Bandana Mask', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'attire.banditguard', name: 'Bandit Guard Gear', category: 'Attire', stack: 1, blueprint: false },
            { shortname: 'barrelcostume', name: 'Barrel Costume', category: 'Attire', stack: 1, blueprint: false },
            { shortname: 'hat.cap', name: 'Baseball Cap', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'hat.beenie', name: 'Beenie Hat', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'bone.armor.suit', name: 'Bone Armor', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'deer.skull.mask', name: 'Bone Helmet', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'hat.boonie', name: 'Boonie Hat', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'shoes.boots', name: 'Boots', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'bucket.helmet', name: 'Bucket Helmet', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'burlap.gloves.new', name: 'Burlap Gloves', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'burlap.headwrap', name: 'Burlap Headwrap', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'burlap.shirt', name: 'Burlap Shirt', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'burlap.shoes', name: 'Burlap Shoes', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'burlap.trousers', name: 'Burlap Trousers', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'hat.candle', name: 'Candle Hat', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'coffeecan.helmet', name: 'Coffee Can Helmet', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'cratecostume', name: 'Crate Costume', category: 'Attire', stack: 1, blueprint: false },
            { shortname: 'diving.fins', name: 'Diving Fins', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'diving.mask', name: 'Diving Mask', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'diving.tank', name: 'Diving Tank', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'boots.frog', name: 'Frog Boots', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'hazmatsuit.frontier', name: 'Frontier Suit', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'hazmatsuit', name: 'Hazmat Suit', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'heavy.plate.helmet', name: 'Heavy Plate Helmet', category: 'Attire', stack: 1, blueprint: false },
            { shortname: 'heavy.plate.jacket', name: 'Heavy Plate Jacket', category: 'Attire', stack: 1, blueprint: false },
            { shortname: 'heavy.plate.pants', name: 'Heavy Plate Pants', category: 'Attire', stack: 1, blueprint: false },
            { shortname: 'attire.hide.boots', name: 'Hide Boots', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'attire.hide.helterneck', name: 'Hide Halterneck', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'attire.hide.pants', name: 'Hide Pants', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'attire.hide.poncho', name: 'Hide Poncho', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'attire.hide.skirt', name: 'Hide Skirt', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'attire.hide.vest', name: 'Hide Vest', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'hoodie', name: 'Hoodie', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'mask.balaclava', name: 'Improvised Balaclava', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'jacket', name: 'Jacket', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'largebackpack', name: 'Large Backpack', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'burlap.gloves', name: 'Leather Gloves', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'tshirt.long', name: 'Longsleeve T-Shirt', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'lumberjack hoodie', name: 'Lumberjack Hoodie', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'metal.plate.torso', name: 'Metal Chest Plate', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'metal.facemask', name: 'Metal Facemask', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'hat.miner', name: 'Miners Hat', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'nightvisiongoggles', name: 'Night Vision Goggles', category: 'Attire', stack: 1, blueprint: false },
            { shortname: 'pants', name: 'Pants', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'parachute', name: 'Parachute', category: 'Attire', stack: 1, blueprint: false },
            { shortname: 'partyhat', name: 'Party Hat', category: 'Attire', stack: 1, blueprint: false },
            { shortname: 'prinsonerhood', name: 'Prisoner Hood', category: 'Attire', stack: 1, blueprint: false },
            { shortname: 'riot.helmet', name: 'Riot Helmet', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'roadsign.gloves', name: 'Roadsign Gloves', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'roadsign.jacket', name: 'Road Sign Jacket', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'roadsign.kilt', name: 'Road Sign Kilt', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'shirt.collared', name: 'Shirt', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'pants.shorts', name: 'Shorts', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'smallbackpack', name: 'Small Backpack', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'jacket.snow', name: 'Snow Jacket', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'tactical.gloves', name: 'Tactical Gloves', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'shirt.tanktop', name: 'Tank Top', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'tshirt', name: 'T-Shirt', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'diving.wetsuit', name: 'Wetsuit', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'hat.wolf', name: 'Wolf Headdress', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'wood.armor.helmet', name: 'Wood Armor Helmet', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'wood.armor.pants', name: 'Wood Armor Pants', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'wood.armor.jacket', name: 'Wood Chestplate', category: 'Attire', stack: 1, blueprint: true },

            // Horse gear
            { shortname: 'horse.shoes.basic', name: 'Basic Horse Shoes', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'horse.saddle.double', name: 'Double Horse Saddle', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'horse.shoes.advanced', name: 'High Quality Horse Shoes', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'horse.saddle', name: 'Horse Saddle', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'hab.armor', name: 'Hot Air Balloon Armor', category: 'Attire', stack: 1, blueprint: false },
            { shortname: 'horse.armor.roadsign', name: 'Roadsign Horse Armor', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'horse.saddlebag', name: 'Saddle bag', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'horse.saddle.single', name: 'Single Horse Saddle', category: 'Attire', stack: 1, blueprint: true },
            { shortname: 'horse.armor.wood', name: 'Wooden Horse Armor', category: 'Attire', stack: 1, blueprint: true },            // ===== TOOLS =====
            { shortname: 'tool.binoculars', name: 'Binoculars', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'cakefiveyear', name: 'Birthday Cake', category: 'Tools', stack: 1, blueprint: false },
            { shortname: 'chainsaw', name: 'Chainsaw', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'flare', name: 'Flare', category: 'Tools', stack: 10, blueprint: true },
            { shortname: 'flashlight.held', name: 'Flashlight', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'hammer', name: 'Hammer', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'handcuffs', name: 'Handcuffs', category: 'Tools', stack: 1, blueprint: false },
            { shortname: 'fishingrod.handmade', name: 'Handmade Fishing Rod', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'hatchet', name: 'Hatchet', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'jackhammer', name: 'Jackhammer', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'metal.detector', name: 'Metal Detector', category: 'Tools', stack: 1, blueprint: false },
            { shortname: 'pickaxe', name: 'Pickaxe', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'pipetool', name: 'Pipe Tool', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'rf.detonator', name: 'RF Transmitter', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'rock', name: 'Rock', category: 'Tools', stack: 1, blueprint: false },
            { shortname: 'axe.salvaged', name: 'Salvaged Axe', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'hammer.salvaged', name: 'Salvaged Hammer', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'icepick.salvaged', name: 'Salvaged Icepick', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'explosive.satchel', name: 'Satchel Charge', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'grenade.smoke', name: 'Smoke Grenade', category: 'Tools', stack: 3, blueprint: true },
            { shortname: 'spraycan', name: 'Spray Can', category: 'Tools', stack: 1, blueprint: false },
            { shortname: 'stonehatchet', name: 'Stone Hatchet', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'stone.pickaxe', name: 'Stone Pickaxe', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'supply.signal', name: 'Supply Signal', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'explosive.timed', name: 'Timed Explosive Charge', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'torch', name: 'Torch', category: 'Tools', stack: 1, blueprint: true },
            { shortname: 'wallpaper.tool', name: 'Wallpaper Tool', category: 'Tools', stack: 1, blueprint: false },
            { shortname: 'bucket.water', name: 'Water Bucket', category: 'Tools', stack: 1, blueprint: true },

            // ===== MEDICAL =====
            { shortname: 'antiradpills', name: 'Anti-Radiation Pills', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'bandage', name: 'Bandage', category: 'Medical', stack: 10, blueprint: true },
            { shortname: 'largemedkit', name: 'Large Medkit', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'syringe.medical', name: 'Medical Syringe', category: 'Medical', stack: 1, blueprint: true },

            // ===== TEAS =====
            { shortname: 'radiationresisttea.advanced', name: 'Advanced Anti-Rad Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'healingtea.advanced', name: 'Advanced Healing Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'maxhealthtea.advanced', name: 'Advanced Max Health Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'oretea.advanced', name: 'Advanced Ore Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'radiationremovetea.advanced', name: 'Advanced Rad. Removal Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'scraptea.advanced', name: 'Advanced Scrap Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'woodtea.advanced', name: 'Advanced Wood Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'radiationresisttea', name: 'Anti-Rad Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'healingtea', name: 'Basic Healing Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'maxhealthtea', name: 'Basic Max Health Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'oretea', name: 'Basic Ore Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'scraptea', name: 'Basic Scrap Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'woodtea', name: 'Basic Wood Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'radiationresisttea.pure', name: 'Pure Anti-Rad Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'healingtea.pure', name: 'Pure Healing Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'maxhealthtea.pure', name: 'Pure Max Health Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'oretea.pure', name: 'Pure Ore Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'radiationremovetea.pure', name: 'Pure Rad. Removal Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'scraptea.pure', name: 'Pure Scrap Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'woodtea.pure', name: 'Pure Wood Tea', category: 'Medical', stack: 1, blueprint: true },
            { shortname: 'radiationremovetea', name: 'Rad. Removal Tea', category: 'Medical', stack: 1, blueprint: true },

            // ===== FOOD =====
            { shortname: 'fish.anchovy', name: 'Anchovy', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'apple', name: 'Apple', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'black.raspberries', name: 'Black Raspberries', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'blueberries', name: 'Blueberries', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'blue.berry', name: 'Blue Berry', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'clone.blue.berry', name: 'Blue Berry Clone', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'seed.blue.berry', name: 'Blue Berry Seed', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'bearmeat.burned', name: 'Burnt Bear Meat', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'chicken.burned', name: 'Burnt Chicken', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'deermeat.burned', name: 'Burnt Deer Meat', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'horsemeat.burned', name: 'Burnt Horse Meat', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'humanmeat.burned', name: 'Burnt Human Meat', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'meat.pork.burned', name: 'Burnt Pork', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'wolfmeat.burned', name: 'Burnt Wolf Meat', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'cactusflesh', name: 'Cactus Flesh', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'can.beans', name: 'Can of Beans', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'can.tuna', name: 'Can of Tuna', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'fish.catfish', name: 'Catfish', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'chocolate', name: 'Chocolate Bar', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'bearmeat.cooked', name: 'Cooked Bear Meat', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'chicken.cooked', name: 'Cooked Chicken', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'deermeat.cooked', name: 'Cooked Deer Meat', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'fish.cooked', name: 'Cooked Fish', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'horsemeat.cooked', name: 'Cooked Horse Meat', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'humanmeat.cooked', name: 'Cooked Human Meat', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'meat.pork.cooked', name: 'Cooked Pork', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'wolfmeat.cooked', name: 'Cooked Wolf Meat', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'corn', name: 'Corn', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'clone.corn', name: 'Corn Clone', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'seed.corn', name: 'Corn Seed', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'granolabar', name: 'Granola Bar', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'green.berry', name: 'Green Berry', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'clone.green.berry', name: 'Green Berry Clone', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'seed.green.berry', name: 'Green Berry Seed', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'grub', name: 'Grub', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'clone.hemp', name: 'Hemp Clone', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'seed.hemp', name: 'Hemp Seed', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'fish.herring', name: 'Herring', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'fish.minnows', name: 'Minnows', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'mushroom', name: 'Mushroom', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'fish.orangeroughy', name: 'Orange Roughy', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'jar.pickle', name: 'Pickles', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'potato', name: 'Potato', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'clone.potato', name: 'Potato Clone', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'seed.potato', name: 'Potato Seed', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'pumpkin', name: 'Pumpkin', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'clone.pumpkin', name: 'Pumpkin Plant Clone', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'seed.pumpkin', name: 'Pumpkin Seed', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'bearmeat', name: 'Raw Bear Meat', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'chicken.raw', name: 'Raw Chicken Breast', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'deermeat.raw', name: 'Raw Deer Meat', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'fish.raw', name: 'Raw Fish', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'horsemeat.raw', name: 'Raw Horse Meat', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'humanmeat.raw', name: 'Raw Human Meat', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'meat.boar', name: 'Raw Pork', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'wolfmeat.raw', name: 'Raw Wolf Meat', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'red.berry', name: 'Red Berry', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'clone.red.berry', name: 'Red Berry Clone', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'seed.red.berry', name: 'Red Berry Seed', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'fish.salmon', name: 'Salmon', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'fish.sardine', name: 'Sardine', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'fish.smallshark', name: 'Small Shark', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'fish.troutsmall', name: 'Small Trout', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'smallwaterbottle', name: 'Small Water Bottle', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'waterjug', name: 'Water Jug', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'white.berry', name: 'White Berry', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'clone.white.berry', name: 'White Berry Clone', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'seed.white.berry', name: 'White Berry Seed', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'worm', name: 'Worm', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'yellow.berry', name: 'Yellow Berry', category: 'Food', stack: 10, blueprint: false },
            { shortname: 'clone.yellow.berry', name: 'Yellow Berry Clone', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'seed.yellow.berry', name: 'Yellow Berry Seed', category: 'Food', stack: 1, blueprint: false },
            { shortname: 'fish.yellowperch', name: 'Yellow Perch', category: 'Food', stack: 10, blueprint: false },

            // ===== TRAPS =====
            { shortname: 'flameturret', name: 'Flame Turret', category: 'Traps', stack: 1, blueprint: true },
            { shortname: 'trap.landmine', name: 'Landmine', category: 'Traps', stack: 1, blueprint: true },
            { shortname: 'samsite', name: 'SAM Site', category: 'Traps', stack: 1, blueprint: true },
            { shortname: 'guntrap', name: 'Shotgun Trap', category: 'Traps', stack: 1, blueprint: true },
            { shortname: 'trap.bear', name: 'Snap Trap', category: 'Traps', stack: 1, blueprint: true },
            { shortname: 'spikes.floor', name: 'Wooden Floor Spikes', category: 'Traps', stack: 1, blueprint: true },

            // ===== MISCELLANEOUS =====
            { shortname: 'keycard_blue', name: 'Blue Keycard', category: 'Misc', stack: 1, blueprint: false },
            { shortname: 'door.key', name: 'Door Key', category: 'Misc', stack: 1, blueprint: false },
            { shortname: 'keycard_green', name: 'Green Keycard', category: 'Misc', stack: 1, blueprint: false },
            { shortname: 'fun.guitar', name: 'Guitar', category: 'Misc', stack: 1, blueprint: false },
            { shortname: 'note', name: 'Note', category: 'Misc', stack: 1, blueprint: false },
            { shortname: 'keycard_red', name: 'Red Keycard', category: 'Misc', stack: 1, blueprint: false },

            // ===== COMPONENTS =====
            { shortname: 'fuse', name: 'Electric Fuse', category: 'Components', stack: 1, blueprint: false },
            { shortname: 'propanetank', name: 'Empty Propane Tank', category: 'Components', stack: 1, blueprint: false },
            { shortname: 'gears', name: 'Gears', category: 'Components', stack: 10, blueprint: false },
            { shortname: 'metalblade', name: 'Metal Blade', category: 'Components', stack: 10, blueprint: false },
            { shortname: 'metalpipe', name: 'Metal Pipe', category: 'Components', stack: 10, blueprint: false },
            { shortname: 'metalspring', name: 'Metal Spring', category: 'Components', stack: 10, blueprint: false },
            { shortname: 'aiming.module.mlrs', name: 'MLRS Aiming Module', category: 'Components', stack: 1, blueprint: false },
            { shortname: 'riflebody', name: 'Rifle Body', category: 'Components', stack: 1, blueprint: false },
            { shortname: 'roadsigns', name: 'Road Signs', category: 'Components', stack: 10, blueprint: false },
            { shortname: 'rope', name: 'Rope', category: 'Components', stack: 10, blueprint: false },
            { shortname: 'semibody', name: 'Semi Automatic Body', category: 'Components', stack: 1, blueprint: false },
            { shortname: 'sewingkit', name: 'Sewing Kit', category: 'Components', stack: 10, blueprint: false },
            { shortname: 'sheetmetal', name: 'Sheet Metal', category: 'Components', stack: 10, blueprint: false },
            { shortname: 'smgbody', name: 'SMG Body', category: 'Components', stack: 1, blueprint: false },
            { shortname: 'tarp', name: 'Tarp', category: 'Components', stack: 10, blueprint: false },
            { shortname: 'techparts', name: 'Tech Trash', category: 'Components', stack: 10, blueprint: false },

            // ===== ELECTRICAL =====
            { shortname: 'electric.andswitch', name: 'AND Switch', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.audioalarm', name: 'Audio Alarm', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'autoturret', name: 'Auto Turret', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.blocker', name: 'Blocker', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.button', name: 'Button', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'ceilinglight', name: 'Ceiling Light', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'computerstation', name: 'Computer Station', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.counter', name: 'Counter', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.doorcontroller', name: 'Door Controller', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'drone', name: 'Drone', category: 'Electrical', stack: 1, blueprint: false },
            { shortname: 'electrical.branch', name: 'Electrical Branch', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.furnace', name: 'Electric Furnace', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.heater', name: 'Electric Heater', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'elevator', name: 'Elevator', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.flasherlight', name: 'Flasher Light', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'fluid.combiner', name: 'Fluid Combiner', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'fluid.splitter', name: 'Fluid Splitter', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'fluid.switch', name: 'Fluid Switch & Pump', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.hbhfsensor', name: 'HBHF Sensor', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'hosetool', name: 'Hose Tool', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.igniter', name: 'Igniter', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'industrial.combiner', name: 'Industrial Combiner', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'industrial.conveyor', name: 'Industrial Conveyor', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'industrial.crafter', name: 'Industrial Crafter', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'industrial.splitter', name: 'Industrial Splitter', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.battery.rechargable.large', name: 'Large Rechargeable Battery', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.solarpanel.large', name: 'Large Solar Panel', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.laserdetector', name: 'Laser Detector', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.battery.rechargable.medium', name: 'Medium Rechargeable Battery', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electrical.memorycell', name: 'Memory Cell', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'modularcarlift', name: 'Modular Car Lift', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.orswitch', name: 'OR Switch', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'powered.water.purifier', name: 'Powered Water Purifier', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.pressurepad', name: 'Pressure Pad', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.random.switch', name: 'RAND Switch', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'target.reactive', name: 'Reactive Target', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.rf.broadcaster', name: 'RF Broadcaster', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'rf_pager', name: 'RF Pager', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.rf.receiver', name: 'RF Receiver', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electrical.combiner', name: 'Root Combiner', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'searchlight', name: 'Search Light', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.seismicsensor', name: 'Seismic Sensor', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.sirenlight', name: 'Siren Light', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.battery.rechargable.small', name: 'Small Rechargeable Battery', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.fuelgenerator.small', name: 'Small Generator', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.splitter', name: 'Splitter', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.sprinkler', name: 'Sprinkler', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'storageadapter', name: 'Storage Adapter', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'storage.monitor', name: 'Storage Monitor', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.switch', name: 'Switch', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.teslacoil', name: 'Tesla Coil', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.generator.small', name: 'Test Generator', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.timer', name: 'Timer', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'waterpump', name: 'Water Pump', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'generator.wind.scrap', name: 'Wind Turbine', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'wiretool', name: 'Wire Tool', category: 'Electrical', stack: 1, blueprint: true },
            { shortname: 'electric.xorswitch', name: 'XOR Switch', category: 'Electrical', stack: 1, blueprint: true },

            // ===== ANIMALS =====
            { shortname: 'bear', name: 'Bear', category: 'Animals', stack: 1, blueprint: false },
            { shortname: 'boar', name: 'Boar', category: 'Animals', stack: 1, blueprint: false },
            { shortname: 'chicken', name: 'Chicken', category: 'Animals', stack: 1, blueprint: false },
            { shortname: 'horse', name: 'Horse', category: 'Animals', stack: 1, blueprint: false },
            { shortname: 'shark', name: 'Shark', category: 'Animals', stack: 1, blueprint: false },
            { shortname: 'stag', name: 'Stag', category: 'Animals', stack: 1, blueprint: false },
            { shortname: 'ridablehorse', name: 'Ridable Horse', category: 'Animals', stack: 1, blueprint: false },
            { shortname: 'wolf', name: 'Wolf', category: 'Animals', stack: 1, blueprint: false },

            // ===== VEHICLES =====
            { shortname: 'attackhelicopter', name: 'Attack Helicopter', category: 'Vehicles', stack: 1, blueprint: false },
            { shortname: 'hotairballoon', name: 'Hot Air Balloon', category: 'Vehicles', stack: 1, blueprint: false },
            { shortname: 'minicopter', name: 'Minicopter', category: 'Vehicles', stack: 1, blueprint: false },
            { shortname: 'scraptransporthelicopter', name: 'Transport Helicopter', category: 'Vehicles', stack: 1, blueprint: false },
            { shortname: 'pedalbike', name: 'Bicycle', category: 'Vehicles', stack: 1, blueprint: true },
            { shortname: 'pedaltrike', name: 'Tricycle', category: 'Vehicles', stack: 1, blueprint: true },
            { shortname: 'motorbike', name: 'Motorbike', category: 'Vehicles', stack: 1, blueprint: true },
            { shortname: 'motorbike_sidecar', name: 'Motorbike with Sidecar', category: 'Vehicles', stack: 1, blueprint: true },
            { shortname: '2module_car', name: '2 Module Car', category: 'Vehicles', stack: 1, blueprint: true },
            { shortname: '3module_car', name: '3 Module Car', category: 'Vehicles', stack: 1, blueprint: true },
            { shortname: '4module_car', name: '4 Module Car', category: 'Vehicles', stack: 1, blueprint: true },
            { shortname: 'magnetcrane', name: 'Magnet Crane', category: 'Vehicles', stack: 1, blueprint: false },

            // ===== VEHICLE PARTS =====
            { shortname: 'vehicle.1mod.cockpit.armored', name: 'Armored Cockpit Vehicle Module', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'vehicle.1mod.passengers.armored', name: 'Armored Passenger Vehicle Module', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'vehicle.2mod.camper', name: 'Camper Vehicle Module', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'vehicle.1mod.cockpit', name: 'Cockpit Vehicle Module', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'vehicle.1mod.cockpit.with.engine', name: 'Cockpit With Engine Vehicle Module', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'vehicle.1mod.engine', name: 'Engine Vehicle Module', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'vehicle.1mod.flatbed', name: 'Flatbed Vehicle Module', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'vehicle.2mod.fuel.tank', name: 'Fuel Tank Vehicle Module', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'vehicle.2mod.flatbed', name: 'Large Flatbed Vehicle Module', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'vehicle.2mod.passengers', name: 'Passenger Vehicle Module', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'vehicle.1mod.rear.seats', name: 'Rear Seats Vehicle Module', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'vehicle.1mod.storage', name: 'Storage Vehicle Module', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'vehicle.1mod.taxi', name: 'Taxi Vehicle Module', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'carburetor1', name: 'Low Quality Carburetor', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'carburetor2', name: 'Medium Quality Carburetor', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'carburetor3', name: 'High Quality Carburetor', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'crankshaft1', name: 'Low Quality Crankshaft', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'crankshaft2', name: 'Medium Quality Crankshaft', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'crankshaft3', name: 'High Quality Crankshaft', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'piston1', name: 'Low Quality Pistons', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'piston2', name: 'Medium Quality Pistons', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'piston3', name: 'High Quality Pistons', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'sparkplug1', name: 'Low Quality Spark Plugs', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'sparkplug2', name: 'Medium Quality Spark Plugs', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'sparkplug3', name: 'High Quality Spark Plugs', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'valve1', name: 'Low Quality Valves', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'valve2', name: 'Medium Quality Valves', category: 'Vehicle Parts', stack: 1, blueprint: true },
            { shortname: 'valve3', name: 'High Quality Valves', category: 'Vehicle Parts', stack: 1, blueprint: true },

            // ===== SEASONAL - EASTER =====
            { shortname: 'easter.bronzeegg', name: 'Bronze Egg', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'attire.bunnyears', name: 'Bunny Ears', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'attire.bunny.onesie', name: 'Bunny Onesie', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'easterbasket', name: 'Egg Basket', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'easter.goldegg', name: 'Gold Egg', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'easter.paintedeggs', name: 'Painted Egg', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'easter.silveregg', name: 'Silver Egg', category: 'Seasonal', stack: 1, blueprint: false },

            // ===== SEASONAL - HALLOWEEN =====
            { shortname: 'knife.butcher', name: 'Butcher Knife', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'coffin.storage', name: 'Coffin', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'gravestone', name: 'Gravestone', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'wall.graveyard.fence', name: 'Graveyard Fence', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'halloween.candy', name: 'Halloween Candy', category: 'Seasonal', stack: 10, blueprint: false },
            { shortname: 'halloween.lootbag.large', name: 'Large Loot Bag', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'halloween.lootbag.medium', name: 'Medium Loot Bag', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'halloween.mummysuit', name: 'Mummy Suit', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'pitchfork', name: 'Pitchfork', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'pumpkinbasket', name: 'Pumpkin Bucket', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'scarecrow', name: 'Scarecrow', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'scarecrow.suit', name: 'Scarecrow Suit', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'scarecrowhead', name: 'Scarecrow Wrap', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'sickle', name: 'Sickle', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'halloween.lootbag.small', name: 'Small LootBag', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'spiderweb', name: 'Spider Webs', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'woodcross', name: 'Wooden Cross', category: 'Seasonal', stack: 1, blueprint: false },

            // ===== SEASONAL - XMAS =====
            { shortname: 'candycane', name: 'Candy Cane', category: 'Seasonal', stack: 10, blueprint: false },
            { shortname: 'candycaneclub', name: 'Candy Cane Club', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'xmas.lightstring', name: 'Christmas Lights', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'xmas.tree', name: 'Christmas Tree', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'coal', name: 'Coal', category: 'Seasonal', stack: 10, blueprint: false },
            { shortname: 'xmas.decoration.baubels', name: 'Decorative Baubels', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'xmas.decoration.gingerbreadmen', name: 'Decorative Gingerbread Men', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'xmas.decoration.pinecone', name: 'Decorative Pinecones', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'xmas.decoration.candycanes', name: 'Decorative Plastic Candy Canes', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'xmas.decoration.tinsel', name: 'Decorative Tinsel', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'gingerbreadsuit', name: 'Gingerbread Suit', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'wall.external.high.ice', name: 'High Ice Wall', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'xmas.present.large', name: 'Large Present', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'stocking.large', name: 'Large Stocking', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'xmas.present.medium', name: 'Medium Present', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'pookie.bear', name: 'Pookie Bear', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'attire.reindeer.headband', name: 'Reindeer Antlers', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'santahat', name: 'Santa Hat', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'wall.ice.wall', name: 'Short Ice Wall', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'xmas.present.small', name: 'Small Present', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'stocking.small', name: 'Small Stocking', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'snowball', name: 'Snowball', category: 'Seasonal', stack: 10, blueprint: false },
            { shortname: 'snowballgun', name: 'Snowball Gun', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'xmas.decoration.star', name: 'Star Tree Topper', category: 'Seasonal', stack: 1, blueprint: false },
            { shortname: 'xmas.decoration.lights', name: 'Tree Lights', category: 'Seasonal', stack: 1, blueprint: false }
        ];
    }

    // Helper method to get all items
    getAllItems() {
        return this.items;
    }

    // Get items by category
    getItemsByCategory(category) {
        return this.items.filter(item => item.category === category);
    }

    // Search items by name or shortname
    searchItems(query) {
        const lowerQuery = query.toLowerCase();
        return this.items.filter(item => 
            item.name.toLowerCase().includes(lowerQuery) || 
            item.shortname.toLowerCase().includes(lowerQuery)
        );
    }

    // Get item by shortname
    getItemByShortname(shortname) {
        return this.items.find(item => item.shortname === shortname);
    }
}

// Initialize when tablet is ready
document.addEventListener('DOMContentLoaded', () => {
    window.itemsDatabase = new ItemsDatabase();
});